### ISSUE TITLE
Extension contains analytics code from Dart-Code

### ISSUE THREAD

**Issue by DanTup** [waseemdev/vscode-flutter.xml-layout#1]
Hi!

I noticed this extension has a copy of some of the code from the Dart extension - including the analytics code:

https://github.com/waseemdev/vscode-flutter.xml-layout/blob/master/src/dart/extension/analytics.ts

I don't know if the code is actually called, but sending analytics to this account from your extension could be confusing - is it possible you can remove the analytics code (or change the ID for the anlytics account?).

Thanks!

**Comment by waseemdev** [comment]
Hi

Yes, I used some code from Dart extension to provide language features (code completion,, hover info go to definition..). The code related to analytics is not being called, anyway, I'll remove it and update the extension soon.

Thank you

**Comment by DanTup** [comment]
Thanks!

> Yes, I used some code from Dart extension to provide language features (code completion,, hover info go to definition..)

Out of interest - how are you reusing this? (I couldn't find obvious code doing it). If you're spawning your own version of the analysis server (and the Dart extension is spawning its own too), you might consume far more resources than  you need to. You may be able to reuse a lot of the functionality from the Dart extension by calling the VS Code commands (for ex. `vscode.executeHoverProvider`, `vscode.executeCompletionItemProvider`, etc.) and that wouldn't require copying (and maintaining) and code from the Dart extension (it's also have a much more stable API).

**Comment by waseemdev** [comment]
I'm using a custom provider and registering it using `language.registerCompletionItemProvider`, and calling `analyzer.completionGetSuggestionsResults` (which is exported by Dart ext.).
Actually I didn't know about these commands, but also we need to register a provider to execute them instead of calling `analyzer.*` isn't?

**Comment by DanTup** [comment]
Oh, I see, using `_privateApi`:

https://github.com/waseemdev/vscode-flutter.xml-layout/blob/fa20e8dfd1d1e8b13f8ebc53c77be7618a747793/src/extension.ts#L36

This is dangerous :) That API is exported *only* so it can be used in our integration tests (it used to be a `Symbol()` so you can't do that, but now that it's web-pack'd and our tests are "outside" we had to change it). That API could change literally at any time (I change it frequently when working on tests - recently I've been removing things from it as I change more tests to not require them so I can run them for LSP).

> Actually I didn't know about these commands, but also we need to register a provider to execute them instead of calling analyzer.* isn't?

Yeah, you'd still need to register a provider - but it would allow you to call the Dart extension's providers. I don't know how well it'd work as I'm not sure what you're currently calling. If you had a position in a `.dart` file, you could call `commands.executeCommand("vscode.executeCompletionItemProvider", uri, position)` and VS Code would then call our provider and give you the results. This is a stable API we can't break.

The commands are documented here:

https://code.visualstudio.com/api/references/commands

**Comment by waseemdev** [comment]
I see, I'll update the code to use vscode commands.
But how would I implement diagnostics? currently I am calling `analyzer.registerForAnalysisErrors`.

**Comment by DanTup** [comment]
You could use `languages.onDidChangeDiagnostics`:

https://code.visualstudio.com/api/references/vscode-api#languages.onDidChangeDiagnostics

I can't say for sure that everything you need will be available via Code APIs, but it's definitely worth a look - those APIs would be stable and never change, whereas I can't make any commitment about the private APIs we use for testing, as the internal code is changed frequently (and on the LSP branch there are significant likely to merge in the coming months).

If you think there's anything you can't get without using the private API, let me know and I can see if I can find a stable way.

**Comment by waseemdev** [comment]
I've removed the dependency of Dart Code extension and replaced it with vscode commands, so far all good except for `documentation` field of completion items is getting null when calling `vscode.executeCompletionItemProvider`.
Also, how to implement `CompletionItemProvider.resolveCompletionItem()`. previously, I was calling `analyzer.completionGetSuggestionDetails()`.

Another issue if you could help me understand it (not specific to Dart Code ext):
The way the completion works, in my understanding, is by passing the file Uri and Position to the LSP server, then the server will access the file and do some magic and returns completion items to the client, if this is true, then how it handles the changes that is happening online (user didn't save the file)?

A similar thing I've noticed is the synchronization between Android Studio and VS Code while you're typing in a file that is open in both editors.
Do you have any thoughts on this?

Thank you for your time.

**Comment by DanTup** [comment]
> except for documentation field of completion items is getting null when calling `vscode.executeCompletionItemProvider`.
> Also, how to implement `CompletionItemProvider.resolveCompletionItem()`. previously, I was calling `analyzer.completionGetSuggestionDetails()`

When you call [`executeCompletionItemProvider`](https://code.visualstudio.com/api/references/commands), the 4th argument is `itemResolveCount` which tells it how many items to call resolve for (the higher the number, the greater the impact on performance, ofcourse).

How are you using this data? If VS Code is showing the completion list, it would resolve the items automatically. I don't know if there's an API (besides opening the completion list and moving through them) to have them resolved invidiaully (though maybe there should be - it might be worth opening a VS Code feature request and explaining your use case).

> The way the completion works, in my understanding, is by passing the file Uri and Position to the LSP server...

FWIW, right now Dart isn't using LSP, but its own protocol. I have been adding LSP support to the analysis server, but VS Code hasn't yet moved over to it - though I'd like to do that. When it does move over, some of the things discussed here may change slightly, as all of the providers in the Dart extension will go aware, since the LSP client contains its own code for that.

> ... then the server will access the file and do some magic and returns completion items to the client, if this is true, then how it handles the changes that is happening online (user didn't save the file)?

When you open a file, we inform the server that the editor is now in control of that file, and we tell it when changes are being made (by sending deltas of the edits). The server will then user that version (instead of what's on disk) when analyzing (this inclueds diagnostics, hovers, competion, symbols, etc.). While you're editing code in the editor, those changes are transmitted to the analysis/LSP server too, so it keeps track of the unsaved file contents. When you close a file, we tell the server (in LSP it's a didCloseDocument event, and in the DAS protocol we "remove the overlay") and it goes back to using the contents from disk.

> A similar thing I've noticed is the synchronization between Android Studio and VS Code while you're typing in a file that is open in both editors.

I'm not sure exactly what you mean here. I wouldn't expect anything to be synchronised, as each editor keeps its own copy of the server + state. However, if you have auto-save enabled, it's possible that one editor saves changes and then the other sees the file on disk changed and loads it?

**Comment by waseemdev** [comment]
`itemResolveCount` seems doesn't work at all.
What about `CompletionItem.documentation` property why is null?

> if you have auto-save enabled, it's possible...

Indeed it was because of auto-save.

**Comment by DanTup** [comment]
> `itemResolveCount` seems doesn't work at all.

I use this in some tests, so I'm sure it works - but you need to resolve enough to include the item (eg. if you resolve 100 but there are 1000 items, then 900 will be unresolved). It's not a very good way if you need to resolve a specific item. It's hard to suggest anything else without understanding what you're doing though.

> What about `CompletionItem.documentation` property why is null?

A few possible reasons:

1. It's only populated during `resolve`, so if your resolve isn't working, you won't get docs. You *might* be able to read `_documentation` as an alternative, since we stash the docs there while waiting for resolve (the reason we don't include it initially is to avoid huge JSON packets going from the extension host to VS Code - it's a lot to run through serislisation/deserialisation):

https://github.com/Dart-Code/Dart-Code/blob/0c0d2dbcf13e2c708cd4d068516b07f752708921/src/extension/providers/dart_completion_item_provider.ts#L144

2. If you're on a new SDK, the documentation is being removed from completion for performance reasons (see https://github.com/dart-lang/sdk/issues/37816). If/when we move over to LSP, it will come back (since the LSP server provides it in the resolve method), but in the short-term, this documentation will be unavailable in completions (though still available in things like hovers).

**Comment by waseemdev** [comment]
These are the common cases that use completion from inside XML file:
- Tag completion: which gets all classes (this resolves +5000 items).
In this case what I'm doing is passing the Uri of the `file.xml.dart` (generated one) with the first position inside `Widget build(BuildContext context)`, then filtering them to get the classes only. this works fine.
- Attribute completion: which gets all fields of a specific class.
Here I pass the position of the class and the file Uri. this works fine except if the user didn't save the file, in this case the fields will not be resolved, because the class is not generated in the `xml.dart` file yet so I can't get its position.
- Attribute value completion: I don't know how to do it properly :)

**Comment by DanTup** [comment]
> Here I pass the position of the class and the file Uri. this works fine except if the user didn't save the file, in this case the fields will not be resolved, because the class is not generated in the xml.dart file yet so I can't get its position

Handling this would be tricky. You'd probably have to regenerate the file as it changes (not on save) either on-disk or in an open editor so it was transmitted to the server.

Another possible option could be to make an analysis server plugin that can handle these requests directly. I don't know how complicated that would be though (I know very little about the plugins, though a Dart-Code user has been using them to handle custom file types - see https://github.com/Dart-Code/Dart-Code/issues/1981).

> Attribute value completion: I don't know how to do it properly :)

Probably the same answer as above - if you can get the server to understand the generated Dart as it changes (rather than saved), you could request completion at the correct location for where this would be inserted (though you may get far more completion that just the attribute).

Sorry I don't have more answers, but hope this helps some!

**Comment by waseemdev** [comment]
Ok I'll make some experiments on that.
Thank you very much!
