### ISSUE TITLE
Failed to generate controller file when there's '.' character in the middle of filepath

### ISSUE THREAD

**Issue by Jamesweng** [waseemdev/vscode-flutter.xml-layout#12]
Hello Waseemdev, 

This extension is awesome and we would love to have a try in our projects. When playing with this extension, we find an issue here: 

The extension failed to generate the controller file if we have a character '.' in the middle of file path, e.g.,

for file: /Users/firstname.lastname/workspace/test-vscode-flutter.xml-layout/home/home.xml

It will try to import 'firstname.ctrl.dart' instead of 'home.ctrl.dart'.  It  looks like the extension splits on the first '.' on the path instead of the last one to generate the filename.

Could you please have a look here?

Thank You!
-James

**Comment by waseemdev** [comment]
Thank you for your PR, but I fixed the issue before I see it :), fixed anyway.

**Comment by Jamesweng** [comment]
Thanks for the quick fix!
