### ISSUE TITLE
itemBuilder for listView generates null item for empty array

### ISSUE THREAD

**Issue by Jamesweng** [waseemdev/vscode-flutter.xml-layout#14]
Hi Waseemdev,

The following xml code - 

```
<ListView :use="builder" :itemBuilder="item of ctrl.data | behavior">
      <Card margin="24" >
     ...

```
will generate codes like this - 

```
 StreamBuilder(
      initialData: ctrl.data.value,
      stream: ctrl.data,
      builder: (BuildContext context, ctrlDataSnapshot) {
        final ctrlDataValue = ctrlDataSnapshot.data;
        if (ctrlDataValue == null) {
          return Container(width: 0, height: 0);
        }
        return ListView.builder(
          itemBuilder: (BuildContext context, int index) {
            final item = ctrlDataValue == null || ctrlDataValue.length <= index || ctrlDataValue.length == 0 ? null : ctrlDataValue[index];
          ...
```

when ctrl.data is an empty array (init value), we get item=null here which may break logic that assumes no code inside the loop will be executed when looping through an empty array, can we handle empty array the same as null array which returns an empty Container(), does this make sense?

Currently to workaround this null item we can add ':if' check inside the loop -

```
<ListView :use="builder" :itemBuilder="item of ctrl.data | behavior">
      <Card margin="24" :if="item!=null" >
     ...
```

Thanks,
-James

**Comment by waseemdev** [comment]
You can also use `itemCount` property if you know the array length.
