### ISSUE TITLE
xml auto import library doesn't work with the latest vscode(1.60.1) & Dart Code(v3.26.0) extension

### ISSUE THREAD

**Issue by Jamesweng** [waseemdev/vscode-flutter.xml-layout#17]
2 issues found after debugging with this extension:

1. the result of executeCommand('vscode.executeCodeActionProvider') not longer returns a 'Import library' titled Command, instead it returns a CodeAction with title 'Import library';

2. got "command '_dart.applySourceChange' not found" when executing the source change command.

**Comment by Jamesweng** [comment]
I created a PR to fix this issue, the solution is use import info from CodeAction title - https://github.com/waseemdev/vscode-flutter.xml-layout/pull/18

**Comment by waseemdev** [comment]
Thanks for the fix, merged.

A side question, do you use this extension with Flutter v2, and does it work properly?

**Comment by Jamesweng** [comment]
Thanks! 
Yes, I use this extension in our App with Flutter v2, it speeds up our UI development a lot!
I don't enable the null-safty feature on our project currently, so no problems for the generated code to run.
