### ISSUE TITLE
FlutterError: This widget has been unmounted, so the State no longer has a context

### ISSUE THREAD

**Issue by Jamesweng** [waseemdev/vscode-flutter.xml-layout#19]
Hi, we got some error reports(collected from Crashlytics) as following on our App - 

"This widget has been unmounted, so the State no longer has a context (and should be considered defunct). Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.. Error thrown during a scheduler callback.

Non-fatal Exception: FlutterError
0  ???                            0x0 State.context.<fn> + 942 (framework.dart:942)
1  ???                            0x0 State.context + 948 (framework.dart:948)
2  ???                            0x0 _ActionButtonWidgetState.initState.<fn> + 41 (action_button_widget.xml.dart:41)
3  ???                            0x0 SchedulerBinding._invokeFrameCallback + 1144 (binding.dart:1144)
4  ???                            0x0 SchedulerBinding.handleDrawFrame + 1089 (binding.dart:1089)
5  ???                            0x0 SchedulerBinding.scheduleWarmUpFrame.<fn> + 862 (binding.dart:862)"

which is related to the following line of generated code which may access the context getter after widget unmounted - 
void initState() { 
    ...
    WidgetsBinding.instance.addPostFrameCallback((_) => ctrl.afterFirstBuild(context));
}

And I'm trying to submit a PR to fix this line.

**Comment by waseemdev** [comment]
Thanks for the fix, I will publish the extension later today.
