### ISSUE TITLE
Working Example

### ISSUE THREAD

**Issue by lilkren** [waseemdev/vscode-flutter.xml-layout#2]
Interesting work. 

Do you have **working sample/example** Flutter Application (with XML Layouts)?

One that illustrates the concepts covered in the [Docs](https://github.com/waseemdev/vscode-flutter.xml-layout/tree/master/docs) would be awesome.

Thanks!

**Comment by waseemdev** [comment]
Thank you for your interest!
I will create an example project and upload it soon.

**Comment by wawandharmawan** [comment]
i'm interesting too.

can i have a basic example.
it would be useful to create.

**Comment by waseemdev** [comment]
Here is an example: https://github.com/waseemdev/flutter_xmllayout_example
