### ISSUE TITLE
0.0.33 upgrade issue on the repeat attribute

### ISSUE THREAD

**Issue by Jamesweng** [waseemdev/vscode-flutter.xml-layout#21]
Hi Waseem,

Thanks for releasing the 0.0.33 update.

After updgrading to 0.0.33, we found one issue and would like to confirm with you - 

the following xml (where cities is a List) - 

<LabeledCheckbox
                          :repeat="item of widget.cities.take(5)"

in 0.0.32, the generated code is -

  ...WidgetHelpers.mapToWidgetList(widget.cities.take(5), (item, index) {

in 0.0.33, the generated code becomes -

...widget.cities.take(5).asMap().map((index, item)) {

is this change expected? it breaks build since the take(5) method returns an iterator that doesn't has a asMap() method
 
Thanks

**Comment by waseemdev** [comment]
Hi Jamesweng,

sorry it was an experiment, I published a new version 0.0.34
