### ISSUE TITLE
I don't understand how to use this technology.

### ISSUE THREAD

**Issue by Gensjava** [waseemdev/vscode-flutter.xml-layout#6]
This library is a great idea, but I have difficulty understanding how to work with it.I follow these instructions, but I don't understand everything.Please explain in more detail or maybe there is an example.
I use Android Studio and I follow these instructions https://marketplace.visualstudio.com/items?itemName=WaseemDev.flutter-xml-layout

but I do not understand where to use this "fxml_app" how do I call this command?

Apply one of the following steps:
Clear all main.dart content then use fxml_app snippet to create the app.
Modify main.dart to use MultiProvider from provider package:
Register PipeProvider (from flutter_xmllayout_helpers package) as a provider.
Register RouteObserver<Route> as a provider (only if you want to use RouteAware events in your widgets' controllers).

**Comment by waseemdev** [comment]
This extension only supports VS Code, so it doesn't work with Android Studio.
Install it and follow the instructions.

> but I do not understand where to use this "fxml_app" how do I call this command?

This is a snippet, just type `fxml_app` in the `main.dart` file then press tab.

**Comment by Gensjava** [comment]
Oh, I'm sorry I didn't notice that it is only for VS Code, maybe you saw the same library for Android Studio or this library is planned to be implemented in Android Studio?

**Comment by Gensjava** [comment]
Everything is fine in VS code everything works.
Great library!!!
