### ISSUE TITLE
How do I use other libraries?

### ISSUE THREAD

**Issue by Gensjava** [waseemdev/vscode-flutter.xml-layout#8]
Hi, I need help, I need to create a carousel I found a library but I don't understand how I can use it I always get an error like this in the screenshot, please help me find solutions.
https://github.com/serenader2014/flutter_carousel_slider

![1](https://user-images.githubusercontent.com/7747716/88497642-9d4f2b00-cf86-11ea-8d83-ba1026f97693.png)
![2](https://user-images.githubusercontent.com/7747716/88497644-9de7c180-cf86-11ea-8fe2-25f923f84416.png)

**Comment by waseemdev** [comment]
Your are doing it right!
Make sure the library is installed properly, to check that, use the library in any dart file and see if it works:
```dart
import 'package:carousel_slider/carousel_slider.dart';
CarouselSlider();
```

**Comment by Gensjava** [comment]
Thank you so much, it works.
 <CarouselSlider  items ="ctrl.list" options="ctrl.carouselOptions" </CarouselSlider>
