### ISSUE TITLE
How to pass data between controllers

### ISSUE THREAD

**Issue by Gensjava** [waseemdev/vscode-flutter.xml-layout#9]
Hi, there is a question how to pass data between controllers?
I did not find it in your examples.

**Comment by waseemdev** [comment]
Hi
Here is the docs for [parameters](https://github.com/waseemdev/vscode-flutter.xml-layout/blob/master/docs/parameters.md).

1. Add parameter:
```xml
<param type="String" name="paramName"></param>
...
<Text text="ctrl.paramName" />
```
2. Pass it from another widget:
```xml
<MyWidget paramName="'param value'" />
```

**Comment by Gensjava** [comment]
Hi, thanks a lot, it works for me!
